images:
  arm64-rust-riscv-dev-32gb:
    platform: "linux"
    arch: "arm64"
    owner: "405894839083"
    name: "arm64-rust-riscv-dev-32gb"
    ami: "ami-040a96edd406c9478"

runners:
  # runners for running tests
  test-gpu-nvidia:
    family: ["g6", "g5", "g4dn", "g6e"]
    image: ubuntu24-gpu-x64
    cpu: [4, 8, 16, 32]
    disk: default
    spot: capacity-optimized
    extras: s3-cache
    preinstall: |
      nvidia-smi
      nvidia-smi -L
      echo 'CUDA_ARCH=75,86,89' >> $GITHUB_ENV
