[package]
name = "openvm-columns-core"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
p3-keccak-air = { workspace = true }
