[package]
name = "openvm-sha2"
description = "OpenVM library for sha2"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
openvm-sha256-guest = { workspace = true }

[dev-dependencies]
openvm-instructions = { workspace = true }
openvm-stark-sdk = { workspace = true } 
openvm-circuit = { workspace = true, features = ["test-utils", "parallel"] }
openvm-transpiler = { workspace = true }
openvm-sha256-transpiler = { workspace = true }
openvm-sha256-circuit = { workspace = true }
openvm-rv32im-transpiler = { workspace = true }
openvm-toolchain-tests = { workspace = true }
eyre = { workspace = true }

[target.'cfg(not(target_os = "zkvm"))'.dependencies]
sha2 = { workspace = true }
