[workspace]
[package]
name = "openvm-keccak256-program"
version = "0.0.0"
edition = "2021"

[dependencies]
openvm = { path = "../../../crates/toolchain/openvm", features = ["std"] }
openvm-keccak256 = { path = "../../../guest-libs/keccak256" }

[features]
default = []

[profile.profiling]
inherits = "release"
debug = 2

strip = false
