[package]
name = "openvm-columns"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[lib]
proc-macro = true

[dependencies]
openvm-columns-core = { workspace = true }
proc-macro2 = "1.0.92"
quote = "1.0.38"
syn = "2.0.95"