[package]
name = "openvm-sha256-guest"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "Guest extension for Sha256"

[dependencies]
openvm-platform = { workspace = true }

[features]
default = []
