[package]
name = "openvm-algebra-guest"
description = "OpenVM guest library for algebra over rings and fields, including modular and complex field arithmetic."
version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
openvm-algebra-moduli-macros = { workspace = true }
openvm-algebra-complex-macros = { workspace = true }
openvm-rv32im-guest = { workspace = true }
openvm-custom-insn = { workspace = true }
serde-big-array.workspace = true
strum_macros.workspace = true
once_cell = { workspace = true, features = ["race", "alloc"] }

[target.'cfg(not(target_os = "zkvm"))'.dependencies]
num-bigint.workspace = true
halo2curves-axiom = { workspace = true, optional = true }

[dev-dependencies]

[features]
default = []
halo2curves = ["dep:halo2curves-axiom"]
